packages:
  - apps/*
  - libs/*
  - docs/*
catalog:
  '@eslint/eslintrc': ~3.3
  '@mocks-server/main': ~4.1
  '@next/env': ~15.5
  '@testing-library/jest-dom': ~6.8.0
  '@testing-library/react': ~16.3.0
  '@types/jest': ~30.0
  '@types/node': ~24.3
  '@types/react': ~19.1
  '@types/react-dom': ~19.1
  autoprefixer: ~10.4
  connect-livereload: ~0.6
  eslint: ~9.34
  eslint-config-next: ~15.5
  express: ~5.1
  generate-react-cli: ~8.4.9
  jest: ~30.1
  jest-environment-jsdom: ~30.1
  livereload: ~0.10
  motion: ~12.23.12
  next: ~15.5.2
  nodemon: ~3.1
  postcss: ~8.5
  postcss-cli: ~11.0
  react: ~19.1
  react-dom: ~19.1
  swagger-ui-express: ~5.0
  '@tailwindcss/postcss': ~4.1
  tailwindcss: ~4.1
  ts-jest: ~29.4
  typescript: ~5.9.2
  yamljs: ~0.3
  
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
